# Generated by Selenium IDE
import time
from select import select
from selenium.common import NoSuchElementException, ElementNotInteractableException, TimeoutException, \
    StaleElementReferenceException
from selenium.webdriver import ActionChains, Keys
from selenium.webdriver.chrome import webdriver
# from selenium.webdriver.firefox import webdriver

# from selenium.webdriver.firefox.service import Service as FirefoxService
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
# from selenium.webdriver.firefox.service import Service as firefoxService
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.select import Select
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.firefox.service import Service as FirefoxService
from selenium.webdriver.firefox.options import Options as FireFoxOptions

import pytest


@pytest.fixture()
def driver():
    Firefox_driver_binary = r'.\drivers\geckodriver'
    fire_fox_options = FireFoxOptions()
    fire_fox_options.add_argument("--width=810")
    fire_fox_options.add_argument("--height=1080")
    fire_fox_options.set_preference("general.useragent.override",
                                    "Mozilla/5.0 (iPad; CPU OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1")

    ser_firefox = FirefoxService(Firefox_driver_binary)
    driver = webdriver.Firefox(service=ser_firefox, options=fire_fox_options)
    yield driver
    driver.close()
  
def test_testCase5(driver):
    driver.get("https://www.ebay.com/")
    driver.find_element(By.CSS_SELECTOR,"li.hl-cat-nav__js-tab:nth-child(3) > a:nth-child(1)").click()
    time.sleep(3)
    driver.find_element(By.CSS_SELECTOR, "a.b-visualnav__tile:nth-child(1) > div:nth-child(1) > img:nth-child(1)").click()
    time.sleep(3)
    driver.find_element(By.CSS_SELECTOR, "a.b-visualnav__tile:nth-child(1) > div:nth-child(1) > img:nth-child(1)").click()
    time.sleep(3)
    driver.find_element(By.CSS_SELECTOR, "#s0-28-9-0-1\[0\]-0-1\[0\]-0-12-list > li:nth-child(1) > a:nth-child(1) > div:nth-child(1) > img:nth-child(1)").click()
    time.sleep(3)
    driver.find_element(By.CSS_SELECTOR,"#s0-28-9-0-1\[0\]-0-1\[0\]-0-12-list > li:nth-child(1) > a:nth-child(1) > div:nth-child(1) > img:nth-child(1)").click()
    time.sleep(5)
    driver.find_element(By.CSS_SELECTOR, "#s0-28_1-9-0-1\[0\]-0-0-12-list > li:nth-child(1) > a:nth-child(1) > div:nth-child(1) > div:nth-child(1) > img:nth-child(1)").click()
    time.sleep(5)
    product_name=driver.find_element(By.CSS_SELECTOR,".x-item-title__mainTitle > span:nth-child(1)").text
    driver.find_element(By.CSS_SELECTOR, "#gh-ac").click()
    time.sleep(2)
    driver.find_element(By.CSS_SELECTOR, "#gh-ac").send_keys(product_name)
    driver.find_element(By.CSS_SELECTOR, "#gh-ac").send_keys(Keys.ENTER)
    time.sleep(5)
    first_res=driver.find_element(By.CSS_SELECTOR,".srp-results > li:nth-child(1) > div:nth-child(1) > div:nth-child(2) > a:nth-child(1) > h3:nth-child(1)").text
    assert product_name==first_res


def test_testCase5_if_in_page(driver):
  driver.get("https://www.ebay.com/")
  driver.find_element(By.CSS_SELECTOR, "li.hl-cat-nav__js-tab:nth-child(3) > a:nth-child(1)").click()
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR, "a.b-visualnav__tile:nth-child(1) > div:nth-child(1) > img:nth-child(1)").click()
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR, "a.b-visualnav__tile:nth-child(1) > div:nth-child(1) > img:nth-child(1)").click()
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR,
                      "#s0-28-9-0-1\[0\]-0-1\[0\]-0-12-list > li:nth-child(1) > a:nth-child(1) > div:nth-child(1) > img:nth-child(1)").click()
  time.sleep(3)
  driver.find_element(By.CSS_SELECTOR,
                      "#s0-28-9-0-1\[0\]-0-1\[0\]-0-12-list > li:nth-child(1) > a:nth-child(1) > div:nth-child(1) > img:nth-child(1)").click()
  time.sleep(5)
  driver.find_element(By.CSS_SELECTOR,
                      "#s0-28_1-9-0-1\[0\]-0-0-12-list > li:nth-child(1) > a:nth-child(1) > div:nth-child(1) > div:nth-child(1) > img:nth-child(1)").click()
  time.sleep(5)
  product_name = driver.find_element(By.CSS_SELECTOR, ".x-item-title__mainTitle > span:nth-child(1)").text
  driver.find_element(By.CSS_SELECTOR, "#gh-ac").click()
  time.sleep(2)
  driver.find_element(By.CSS_SELECTOR, "#gh-ac").send_keys(product_name)
  driver.find_element(By.CSS_SELECTOR, "#gh-ac").send_keys(Keys.ENTER)
  time.sleep(5)
  first_res = driver.find_element(By.CSS_SELECTOR,
                                  ".srp-results > li:nth-child(1) > div:nth-child(1) > div:nth-child(2) > a:nth-child(1) > h3:nth-child(1)").text
  time.sleep(5)
  assert driver.find_element(By.CSS_SELECTOR, ".x-item-title__mainTitle > span:nth-child(1)").is_displayed()
  
