# Generated by Selenium IDE
import time
from select import select
from selenium.common import NoSuchElementException, ElementNotInteractableException, TimeoutException, \
    StaleElementReferenceException
from selenium.webdriver import ActionChains
from selenium.webdriver.chrome import webdriver
# from selenium.webdriver.firefox import webdriver

# from selenium.webdriver.firefox.service import Service as FirefoxService
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
# from selenium.webdriver.firefox.service import Service as firefoxService
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.select import Select
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.firefox.service import Service as FirefoxService
from selenium.webdriver.firefox.options import Options as FireFoxOptions

import pytest


@pytest.fixture()
def driver():
    Firefox_driver_binary = r'.\drivers\geckodriver'
    fire_fox_options = FireFoxOptions()
    fire_fox_options.add_argument("--width=810")
    fire_fox_options.add_argument("--height=1080")
    fire_fox_options.set_preference("general.useragent.override",
                                    "Mozilla/5.0 (iPad; CPU OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1")

    ser_firefox = FirefoxService(Firefox_driver_binary)
    driver = webdriver.Firefox(service=ser_firefox, options=fire_fox_options)
    yield driver
    driver.close()

def test_testCase4_all_incorrect_values (driver):
    driver.get("https://www.ebay.com/")
    driver.find_element(By.LINK_TEXT, "register").click()
    driver.find_element(By.ID, "firstname").click()
    driver.find_element(By.ID, "firstname").send_keys("hdg2324@$%")
    driver.find_element(By.ID, "lastname").send_keys("@$$shd636")
    driver.find_element(By.ID, "Email").send_keys("shfg.sjfh4")
    driver.find_element(By.ID, "password").send_keys("sdjkdfdkjf376373")
    time.sleep(5)
    email_error_msg=driver.find_element(By.CSS_SELECTOR,"#Email_err").text
    expected_msg="Email address is invalid. Please enter a valid email address."
    create_account_btn_html='"<button name="EMAIL_REG_FORM_SUBMIT" id="EMAIL_REG_FORM_SUBMIT" class="btn btn--primary btn--large btn--fluid" disabled="" type="submit" aria-describedby="legalTextId" data-click-tracking-data="{&quot;linkId&quot;:47252,&quot;pageId&quot;:&quot;2560839&quot;,&quot;type&quot;:&quot;_plsr&quot;,&quot;payload&quot;:{&quot;RegModuleName&quot;:&quot;PARTIAL_REG_PERSONAL_EMAIL&quot;,&quot;bs&quot;:206,&quot;ul&quot;:&quot;en-US&quot;,&quot;uc&quot;:100}}">Create account</button>"'
    assert "disabled" in create_account_btn_html
    assert email_error_msg==expected_msg


def test_testCase4_incorrect_first_last_name (driver):
    driver.get("https://www.ebay.com/")
    driver.find_element(By.LINK_TEXT, "register").click()
    driver.find_element(By.ID, "firstname").click()
    first_name="hdg$2324"
    driver.find_element(By.ID, "firstname").send_keys(first_name)
    driver.find_element(By.ID, "lastname").send_keys("@$$shd636")
    driver.find_element(By.ID, "Email").send_keys("jadewed211@serosin.com")
    driver.find_element(By.ID, "password").send_keys("sdjkdfdkjf376373")
    time.sleep(5)
    driver.find_element(By.ID, "EMAIL_REG_FORM_SUBMIT").click()
    try:
      time.sleep(5)
      profile_name = driver.find_element(By.CSS_SELECTOR, "b:nth-child(1)").text
      time.sleep(5)
      assert first_name== profile_name
    except NoSuchElementException:
       print("\nno such element")


def test_testCase4_incorrect_first_last_name2 (self):
    driver.get("https://www.ebay.com/")
    driver.find_element(By.LINK_TEXT, "register").click()
    driver.find_element(By.ID, "firstname").click()
    first_name="hdg$2*(%324"
    driver.find_element(By.ID, "firstname").send_keys(first_name)
    driver.find_element(By.ID, "lastname").send_keys("@$$shd636")
    driver.find_element(By.ID, "Email").send_keys("temos35844@runqx.com")
    driver.find_element(By.ID, "password").send_keys("sdjkdfdkjf376373")
    time.sleep(5)
    driver.find_element(By.ID, "EMAIL_REG_FORM_SUBMIT").click()
    time.sleep(5)
    profile_name = driver.find_element(By.CSS_SELECTOR, "b:nth-child(1)").text
    time.sleep(10)
    first_name_error_msg = driver.find_element(By.CSS_SELECTOR, "#firstname_err")
    assert "Please enter a valid name."==first_name_error_msg.text

  #Ebay allows digits and signs with a first name and last name but does not approve all the signs
