# Generated by Selenium IDE
import time
from select import select
from selenium.common import NoSuchElementException, ElementNotInteractableException, TimeoutException, \
    StaleElementReferenceException
from selenium.webdriver import ActionChains
from selenium.webdriver.chrome import webdriver
# from selenium.webdriver.firefox import webdriver

# from selenium.webdriver.firefox.service import Service as FirefoxService
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
# from selenium.webdriver.firefox.service import Service as firefoxService
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.select import Select
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.firefox.service import Service as FirefoxService
from selenium.webdriver.firefox.options import Options as FireFoxOptions

import pytest


@pytest.fixture()
def driver():
    Firefox_driver_binary = r'.\drivers\geckodriver'
    fire_fox_options = FireFoxOptions()
    fire_fox_options.add_argument("--width=810")
    fire_fox_options.add_argument("--height=1080")
    fire_fox_options.set_preference("general.useragent.override",
                                    "Mozilla/5.0 (iPad; CPU OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1")

    ser_firefox = FirefoxService(Firefox_driver_binary)
    driver = webdriver.Firefox(service=ser_firefox, options=fire_fox_options)
    yield driver
    driver.close()

def test_testCase3(driver):
    driver.get("https://www.ebay.com/")
    driver.find_element(By.LINK_TEXT, "register").click()
    driver.find_element(By.ID, "firstname").click()
    driver.find_element(By.ID, "lastname").click()
    driver.find_element(By.ID, "Email").click()
    driver.find_element(By.ID, "password").click()
    driver.find_element(By.CSS_SELECTOR, ".wrapperConsolidator").click()
    first_name_error_msg=driver.find_element(By.CSS_SELECTOR,"#firstname_err")
    last_name_error_msg=driver.find_element(By.CSS_SELECTOR,"#lastname_err")
    email_error_msg=driver.find_element(By.CSS_SELECTOR,"#Email_err")
    password_error_msg=driver.find_element(By.CSS_SELECTOR,"#password_err")
    assert "Please enter your first name"==first_name_error_msg.text
    assert "Please enter your last name" == last_name_error_msg.text
    assert "Please enter your email address." == email_error_msg.text
    assert "Please enter a password." == password_error_msg.text




