# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options

class TestTestcase6():
  def setup_method(self, method):
    chrome_driver_binary = r'.\drivers\chromedriver'
    self.vars = {
      'browser_name': "chrome_mobile"
    }

    if self.vars["browser_name"] == "chrome":
      self.driver = webdriver.Chrome(chrome_driver_binary)
    elif self.vars["browser_name"] == "chrome_mobile":
      mobile_emulation = {
        "deviceMetrics": {"width": 375, "height": 812, "pixelRatio": 3.0},
        "userAgent": "Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 5 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19"
      }

      chrome_options = Options()
      chrome_options.add_experimental_option("mobileEmulation", mobile_emulation)

      self.driver = webdriver.Chrome(chrome_driver_binary,options=chrome_options)

  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testcase6_step1(self):
    self.driver.get("https://www.ebay.com/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.LINK_TEXT, "Sign in").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "userid").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "userid").send_keys("firecak226@serosin.com")
    time.sleep(3)
    self.driver.find_element(By.ID, "signin-continue-btn").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "pass").send_keys("991594123rami")
    time.sleep(3)
    # self.driver.find_element(By.ID, "sgnBt").click()
    element = self.driver.find_element(By.ID, "sgnBt")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    element.send_keys(Keys.ENTER)
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "#mainContent > div.hl-cat-nav > ul > li:nth-child(3) > a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    time.sleep(3)
    self.driver.find_element(By.LINK_TEXT, "Apple").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".b-visualnav__tile:nth-child(1) .b-img").click()
    # element = self.driver.find_element(By.CSS_SELECTOR, ".carousel__snap-point:nth-child(1) .b-img")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR,"#s0-28-9-0-1\[1\]-0-0-12-list > li:nth-child(1) > a > div.b-info > div.b-info__title").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".carousel__snap-point:nth-child(1) .b-img").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "isCartBtn_btn").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".call-to-action").click()
    # self.driver.find_element(By.CSS_SELECTOR, "#selectable-render-summary67503").click()
    # time.sleep(15)
    # element = self.driver.find_element(By.ID, "selectable-render-summary69133")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    # element = self.driver.find_element(By.CSS_SELECTOR, "body")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element, 0, 0).perform()
    # paypal_expected=self.driver.find_element(By.CSS_SELECTOR,"#page-form > div > div.cta-message-wrapper > div > span > span").text
    time.sleep(5)
    assert "checkout" in  self.driver.title.lower()


  def test_testcase6_step2(self):
    self.driver.get("https://www.ebay.com/")
    self.driver.set_window_size(1552, 840)
    element = self.driver.find_element(By.CSS_SELECTOR, "#mainContent > div.hl-cat-nav > ul > li:nth-child(3) > a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    time.sleep(5)
    self.driver.find_element(By.LINK_TEXT, "Apple").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".b-visualnav__tile:nth-child(1) .b-img").click()
    time.sleep(5)
    element = self.driver.find_element(By.CSS_SELECTOR, ".carousel__snap-point:nth-child(1) .b-img")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".carousel__snap-point:nth-child(1) .b-img").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".x-item-title__mainTitle").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR,"#vi-atl-lnk").click()
    time.sleep(5)
    assert "sign in" in self.driver.title.lower()


  def test_testcase6_step3(self):
    self.driver.get("https://www.ebay.com/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.LINK_TEXT, "Sign in").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "userid").click()
    time.sleep(5)
    self.driver.find_element(By.ID, "userid").send_keys("firecak226@serosin.com")
    time.sleep(5)
    self.driver.find_element(By.ID, "signin-continue-btn").click()
    time.sleep(5)
    self.driver.find_element(By.ID, "pass").send_keys("991594123rami")
    time.sleep(5)
    # self.driver.find_element(By.ID, "sgnBt").click()
    element = self.driver.find_element(By.ID, "sgnBt")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    element.send_keys(Keys.ENTER)
    time.sleep(5)
    element = self.driver.find_element(By.CSS_SELECTOR, "#mainContent > div.hl-cat-nav > ul > li:nth-child(3) > a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    time.sleep(5)
    self.driver.find_element(By.LINK_TEXT, "Apple").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".b-visualnav__tile:nth-child(1) .b-img").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".carousel__snap-point:nth-child(1) .b-img")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".carousel__snap-point:nth-child(1) .b-img").click()
    time.sleep(5)
    self.driver.find_element(By.ID, "isCartBtn_btn").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".call-to-action").click()
    select_quantity=self.driver.find_element(By.CSS_SELECTOR,"#s0-0-20-10-11-electro-wireless-1346549252-144195215991-qty\[\]-1-dropdown")
    select_quantity.click()
    time.sleep(5)
    # assert "checkout" in  self.driver.title.lower()

  
